EAA-337 Applicant data capturing pages from application journey
BEIS-Digital-Services/ebss-application-portal pull request #11
Opened 2022-12-05 14:52 UTC by spotla4

Added following pages in application journey with data validation and navigation
1. What is your full name page
2. What is your Date of birth 
3. What is your email address
4. What is your phone number

2022-12-05 15:09 UTC, willappleby requested changes

2022-12-05 15:09 UTC, willappleby commented on Beis.Ebss.ApplicationPortal.Web/Controllers/DateOfBirthController.cs
> +        [HttpPost(RoutePaths.WhatIsYourDateOfBirthPage, Name = RouteNames.WhatIsYourDateOfBirthPage)]
Needs [ValidateAntiForgeryToken] attribute and corresponding anti forgery token emitted in form markup. Same for all other HttpPost action methods.

2022-12-05 16:44 UTC, paulc1983 submitted a review, later dismissed

2022-12-05 17:31 UTC, willappleby requested changes

2022-12-05 17:31 UTC, willappleby commented on Beis.Ebss.ApplicationPortal.Web/Controllers/AlternateFuelPaymentCheckController.cs
> +        [ValidateAntiForgeryToken]
This is good, but I don't see corresponding @Html.AntiForgeryToken() statements within the <form> tags on the views?

2022-12-06 07:22 UTC, spotla4 commented on Beis.Ebss.ApplicationPortal.Web/Controllers/AlternateFuelPaymentCheckController.cs
> +        [ValidateAntiForgeryToken]
I thought the antiforgery token is automatically generated by the Form tag in Razor file and so we don't have to explicitly add it again.  
https://learn.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-7.0#antiforgery-in-aspnet-core

2022-12-06 07:42 UTC, willappleby commented on Beis.Ebss.ApplicationPortal.Web/Controllers/AlternateFuelPaymentCheckController.cs
> +        [ValidateAntiForgeryToken]
Hi @spotla4, sorry yes looks like that's changed since I was last using it. Will approve the PR now.

2022-12-06 07:43 UTC, willappleby approved these changes

2022-12-06 07:54 UTC, willappleby approved these changes

2022-12-06 07:54 UTC, merged